### ISSUE TITLE
add a button to select which FPS we wants.

### ISSUE THREAD

**Issue by allaze-eroler** [YAL-GameMaker-Tools/AseSync23#10]
it would be extra convenient to select which one i wanted it to be played instead of doing it from CLI command... and i had no idea what command is that.

by default, it was set to frames per second instead of frame per game frame.

**Comment by YellowAfterlife** [comment]
That's a request for Sahaun (on [itch](https://sahaun.itch.io/asesync)) - I'm not the person making that application.
