### ISSUE TITLE
Feature request: Allow loading of ASEprite tags as individual sprites

### ISSUE THREAD

**Issue by Vine2D** [YAL-GameMaker-Tools/AseSync23#8]
ASEprite has a feature where you can organize animations in less files using [tags](https://www.aseprite.org/docs/tags/), it's just a small QoL thing but if asesync could sync them as separate sprites such as `my_sprite_idle`, `my_sprite_talking`, `my_sprite_running` etc it would be nice.

**Comment by YellowAfterlife** [comment]
This had been proposed by someone once - what should happen if you have two layers of tags?

**Comment by Vine2D** [comment]
Assuming you mean [this](https://imgur.com/a/tqOSkAp), I would expect it to mimic Aseprite's behavior when you play the animations, which is to say Layer1 would play frames 1-6, and Layer2 would play frames 5-8.

**Comment by YellowAfterlife** [comment]
https://github.com/YAL-GameMaker-Tools/AseSync23/releases/tag/2023-07
